// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGtpKl6xQidP4lV6ABmNDKV3JyO--IwYo',
    appId: '1:909033665102:web:3c9ea04483a9384735c91f',
    messagingSenderId: '909033665102',
    projectId: 'spotify-ad-clone',
    authDomain: 'spotify-ad-clone.firebaseapp.com',
    storageBucket: 'spotify-ad-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr24Svh2Mfl5qB-nCbVmL1j7sBQ_WswEI',
    appId: '1:909033665102:android:ce670a4f666d3d5d35c91f',
    messagingSenderId: '909033665102',
    projectId: 'spotify-ad-clone',
    storageBucket: 'spotify-ad-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiDG6iwgSTGruEWYKTnqAZHR24SJKFy6U',
    appId: '1:909033665102:ios:404c8a71f9ace2b335c91f',
    messagingSenderId: '909033665102',
    projectId: 'spotify-ad-clone',
    storageBucket: 'spotify-ad-clone.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiDG6iwgSTGruEWYKTnqAZHR24SJKFy6U',
    appId: '1:909033665102:ios:404c8a71f9ace2b335c91f',
    messagingSenderId: '909033665102',
    projectId: 'spotify-ad-clone',
    storageBucket: 'spotify-ad-clone.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGtpKl6xQidP4lV6ABmNDKV3JyO--IwYo',
    appId: '1:909033665102:web:bd680fdf93041d0035c91f',
    messagingSenderId: '909033665102',
    projectId: 'spotify-ad-clone',
    authDomain: 'spotify-ad-clone.firebaseapp.com',
    storageBucket: 'spotify-ad-clone.firebasestorage.app',
  );
}
